var lang = {
    UPDATE_UNCHECKED: "UPDATE_UNCHECKED",
    UPDATE_PREDOWNLOAD_VERSION: "UPDATE_PREDOWNLOAD_VERSION",
    UPDATE_DOWNLOADING_VERSION: "UPDATE_DOWNLOADING_VERSION",
    UPDATE_VERSION_LOADED: "UPDATE_VERSION_LOADED",
    UPDATE_PREDOWNLOAD_MANIFEST: "UPDATE_PREDOWNLOAD_MANIFEST",
    UPDATE_DOWNLOADING_MANIFEST: "UPDATE_DOWNLOADING_MANIFEST",
    UPDATE_MANIFEST_LOADED: "UPDATE_MANIFEST_LOADED",
    UPDATE_NEED_UPDATE: "UPDATE_NEED_UPDATE",
    UPDATE_UPDATING: "UPDATE_UPDATING",
    UPDATE_UNZIPPING: "UPDATE_UNZIPPING",
    UPDATE_UP_TO_DATE: "UPDATE_UP_TO_DATE",
    UPDATE_FAIL_TO_UPDATE: "UPDATE_FAIL_TO_UPDATE"
};